# TRMNLP Local Development Configuration
# Documentation: https://github.com/usetrmnl/trmnlp

# Plugin metadata
name: octopus-energy
viewport: full

# Merge variables for local testing
# These will be replaced by real data from your Cloudflare Worker in production
merge_variables:
  electricity:
    kwh: 245.3
    cost_gbp: 61.22
    daily_avg_kwh: 8.7
    peak_time: "18:00"
    month: "February 2026"
  gas:
    kwh: 412.8
    cost_gbp: 28.45
    month: "February 2026"
  carbon_forecast:
    - time: "2026-02-15T12:00:00Z"
      intensity: 85
      index: "low"
    - time: "2026-02-15T12:30:00Z"
      intensity: 92
      index: "low"
    - time: "2026-02-15T13:00:00Z"
      intensity: 125
      index: "moderate"
    - time: "2026-02-15T13:30:00Z"
      intensity: 160
      index: "high"
    - time: "2026-02-15T14:00:00Z"
      intensity: 95
      index: "low"
    - time: "2026-02-15T14:30:00Z"
      intensity: 88
      index: "low"
    - time: "2026-02-15T15:00:00Z"
      intensity: 82
      index: "low"
    - time: "2026-02-15T15:30:00Z"
      intensity: 76
      index: "low"
    - time: "2026-02-15T16:00:00Z"
      intensity: 145
      index: "moderate"
    - time: "2026-02-15T16:30:00Z"
      intensity: 165
      index: "high"
    - time: "2026-02-15T17:00:00Z"
      intensity: 180
      index: "high"
    - time: "2026-02-15T17:30:00Z"
      intensity: 175
      index: "high"
    - time: "2026-02-15T18:00:00Z"
      intensity: 155
      index: "moderate"
    - time: "2026-02-15T18:30:00Z"
      intensity: 135
      index: "moderate"
    - time: "2026-02-15T19:00:00Z"
      intensity: 110
      index: "moderate"
    - time: "2026-02-15T19:30:00Z"
      intensity: 95
      index: "low"
    - time: "2026-02-15T20:00:00Z"
      intensity: 85
      index: "low"
    - time: "2026-02-15T20:30:00Z"
      intensity: 78
      index: "low"
    - time: "2026-02-15T21:00:00Z"
      intensity: 72
      index: "low"
    - time: "2026-02-15T21:30:00Z"
      intensity: 68
      index: "low"
    - time: "2026-02-15T22:00:00Z"
      intensity: 65
      index: "low"
    - time: "2026-02-15T22:30:00Z"
      intensity: 62
      index: "low"
    - time: "2026-02-15T23:00:00Z"
      intensity: 58
      index: "low"
    - time: "2026-02-15T23:30:00Z"
      intensity: 55
      index: "low"
  carbon_summary:
    green_percentage: 58
    best_window_start: "21:00"
    best_window_end: "06:30"
    next_green_start: null
  last_updated: "2026-02-15T11:30:00Z"
